# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
name:             Brimer
description:      Github Primer CSS toolkit with a 'B', built with Bootstrap 4
baseurl:          /brimer
encoding:         UTF-8

gems:
  - jekyll-sitemap

# Custom vars
current_version:  1.0.1
repo:             https://github.com/websemantics/brimer
